---
- name: ensure sudo is installed
  apt: name=sudo

- name: add {{ provision_admin_group }} group
  group:
    name: '{{ provision_admin_group }}'
    state: present

- name: add {{ provision_admin_group }} to sudoers file
  shell: echo '%{{ provision_admin_group }} ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/{{ provision_admin_group }}

- name: add ansible user
  user:
    name: '{{ item }}'
    shell: /bin/bash
    groups: '{{ provision_admin_group }}'
    append: yes
    state: present
  with_items:
    - ansible

- name: set up authorized keys for ansible
  authorized_key:
    user: ansible
    state: present
    key: '{{ item }}'
  with_file: '{{ ansible_ssh_authorized_keys }}'
